# this data is provided as is for educational purposes only
# no liability is taken for data quality issues 

trackCodes = [
    {'trackCode': 200, 'trackName': 'Wentworth Park', 'State': 'NSW'},
    {'trackCode': 201, 'trackName': 'Dapto', 'State': 'NSW'},
    {'trackCode': 202, 'trackName': 'Bulli', 'State': 'NSW'},
    {'trackCode': 203, 'trackName': 'Casino', 'State': 'NSW'},
    {'trackCode': 204, 'trackName': 'Cessnock', 'State': 'NSW'},    
    {'trackCode': 205, 'trackName': 'Gosford', 'State': 'NSW'},
    {'trackCode': 206, 'trackName': 'Grafton', 'State': 'NSW'}, 
    {'trackCode': 207, 'trackName': 'Lismore', 'State': 'NSW'}, 
    {'trackCode': 208, 'trackName': 'Maitland', 'State': 'NSW'}, 
    {'trackCode': 209, 'trackName': 'Muswellbrook', 'State': 'NSW'}, 
    {'trackCode': 210, 'trackName': 'Newcastle', 'State': 'NSW'}, 
    {'trackCode': 211, 'trackName': 'Nowra', 'State': 'NSW'}, 
    {'trackCode': 212, 'trackName': 'Orange', 'State': 'NSW'}, 
    {'trackCode': 213, 'trackName': 'Penrith', 'State': 'NSW'}, 
    {'trackCode': 214, 'trackName': 'Richmond', 'State': 'NSW'}, 
    {'trackCode': 215, 'trackName': 'Moree', 'State': 'NSW'}, 
    {'trackCode': 216, 'trackName': 'Wyong', 'State': 'NSW'}, 
    {'trackCode': 218, 'trackName': 'Taree', 'State': 'NSW'}, 
    {'trackCode': 219, 'trackName': 'Temora', 'State': 'NSW'}, 
    {'trackCode': 220, 'trackName': 'Wagga Wagga', 'State': 'NSW'}, 
    {'trackCode': 221, 'trackName': 'Wauchope', 'State': 'NSW'}, 
    {'trackCode': 223, 'trackName': 'Albury', 'State': 'NSW'}, 
    {'trackCode': 225, 'trackName': 'Armidale', 'State': 'NSW'}, 
    {'trackCode': 226, 'trackName': 'Bathurst', 'State': 'NSW'}, 
    {'trackCode': 227, 'trackName': 'Broke Hill', 'State': 'NSW'}, 
    {'trackCode': 228, 'trackName': 'Coonabarabran', 'State': 'NSW'}, 
    {'trackCode': 229, 'trackName': 'Coonamble', 'State': 'NSW'}, 
    {'trackCode': 230, 'trackName': 'Cootamundra', 'State': 'NSW'}, 
    {'trackCode': 231, 'trackName': 'Dubbo', 'State': 'NSW'}, 
    {'trackCode': 232, 'trackName': 'Forbes', 'State': 'NSW'}, 
    {'trackCode': 233, 'trackName': 'Goulburn', 'State': 'NSW'}, 
    {'trackCode': 234, 'trackName': 'Griffith', 'State': 'NSW'}, 
    {'trackCode': 235, 'trackName': 'Gunnedah', 'State': 'NSW'}, 
    {'trackCode': 236, 'trackName': 'Harold Park', 'State': 'NSW'}, 
    {'trackCode': 237, 'trackName': 'Kempsey', 'State': 'NSW'}, 
    {'trackCode': 238, 'trackName': 'Lithgow', 'State': 'NSW'}, 
    {'trackCode': 239, 'trackName': 'Moss Vale', 'State': 'NSW'}, 
    {'trackCode': 240, 'trackName': 'Mudgee', 'State': 'NSW'}, 
    {'trackCode': 241, 'trackName': 'Queanbeyan', 'State': 'NSW'}, 
    {'trackCode': 242, 'trackName': 'Tamworth', 'State': 'NSW'}, 
    {'trackCode': 243, 'trackName': 'Wollongong', 'State': 'NSW'}, 
    {'trackCode': 244, 'trackName': 'Young', 'State': 'NSW'}, 
    {'trackCode': 245, 'trackName': 'Cowra', 'State': 'NSW'}, 
    {'trackCode': 246, 'trackName': 'Wentworth', 'State': 'NSW'}, 
    {'trackCode': 247, 'trackName': 'Narrabri', 'State': 'NSW'}, 
    {'trackCode': 248, 'trackName': 'Potts Park', 'State': 'NSW'}, 
    {'trackCode': 249, 'trackName': 'The Gardens', 'State': 'NSW'}, 
    {'trackCode': 250, 'trackName': 'Canberra', 'State': 'NSW'}, 
    {'trackCode': 251, 'trackName': 'Richmond', 'State': 'NSW'}, 
    {'trackCode': 300, 'trackName': 'The Meadows', 'State': 'VIC'}, 
    {'trackCode': 301, 'trackName': 'Sandown Park', 'State': 'VIC'}, 
    {'trackCode': 302, 'trackName': 'Ballarat', 'State': 'VIC'}, 
    {'trackCode': 303, 'trackName': 'Bendigo', 'State': 'VIC'}, 
    {'trackCode': 304, 'trackName': 'Cranbourne', 'State': 'VIC'}, 
    {'trackCode': 305, 'trackName': 'Geelong', 'State': 'VIC'}, 
    {'trackCode': 306, 'trackName': 'Healesville', 'State': 'VIC'}, 
    {'trackCode': 307, 'trackName': 'Horsham', 'State': 'VIC'}, 
    {'trackCode': 308, 'trackName': 'Shepparton', 'State': 'VIC'}, 
    {'trackCode': 309, 'trackName': 'Sale', 'State': 'VIC'}, 
    {'trackCode': 310, 'trackName': 'Traralgon', 'State': 'VIC'}, 
    {'trackCode': 311, 'trackName': 'Wangaratta', 'State': 'VIC'}, 
    {'trackCode': 312, 'trackName': 'Warragul', 'State': 'VIC'}, 
    {'trackCode': 313, 'trackName': 'Warrnambool', 'State': 'VIC'}, 
    {'trackCode': 314, 'trackName': 'Sandown Park', 'State': 'VIC'}, 
    {'trackCode': 315, 'trackName': 'The Meadows', 'State': 'VIC'}, 
    {'trackCode': 363, 'trackName': 'Warrnambool', 'State': 'VIC'}, 
    {'trackCode': 400, 'trackName': 'Albion Park', 'State': 'QLD'}, 
    {'trackCode': 401, 'trackName': 'Beenleigh', 'State': 'QLD'}, 
    {'trackCode': 402, 'trackName': 'Bundaberg', 'State': 'QLD'}, 
    {'trackCode': 403, 'trackName': 'Cairns', 'State': 'QLD'}, 
    {'trackCode': 404, 'trackName': 'Capalaba', 'State': 'QLD'}, 
    {'trackCode': 405, 'trackName': 'Gabba', 'State': 'QLD'}, 
    {'trackCode': 406, 'trackName': 'Gold Coast', 'State': 'QLD'}, 
    {'trackCode': 407, 'trackName': 'Ipswich', 'State': 'QLD'}, 
    {'trackCode': 408, 'trackName': 'Lawnton', 'State': 'QLD'}, 
    {'trackCode': 409, 'trackName': 'Ayr', 'State': 'QLD'}, 
    {'trackCode': 410, 'trackName': 'Mackay', 'State': 'QLD'}, 
    {'trackCode': 411, 'trackName': 'Mt Isa', 'State': 'QLD'}, 
    {'trackCode': 412, 'trackName': 'Rockhampton', 'State': 'QLD'}, 
    {'trackCode': 413, 'trackName': 'Townsville', 'State': 'QLD'}, 
    {'trackCode': 414, 'trackName': 'Toowoomba', 'State': 'QLD'}, 
    {'trackCode': 500, 'trackName': 'Angle Park', 'State': 'SA'}, 
    {'trackCode': 501, 'trackName': 'Barmera', 'State': 'SA'}, 
    {'trackCode': 502, 'trackName': 'Gawler', 'State': 'SA'}, 
    {'trackCode': 503, 'trackName': 'Kulpara', 'State': 'SA'}, 
    {'trackCode': 504, 'trackName': 'Mount Gambier', 'State': 'SA'}, 
    {'trackCode': 505, 'trackName': 'Port Augusta', 'State': 'SA'}, 
    {'trackCode': 506, 'trackName': 'Port Lincoln', 'State': 'SA'}, 
    {'trackCode': 507, 'trackName': 'Port Pirie', 'State': 'SA'}, 
    {'trackCode': 508, 'trackName': 'Strathalbyn', 'State': 'SA'}, 
    {'trackCode': 509, 'trackName': 'Whyalla', 'State': 'SA'}, 
    {'trackCode': 510, 'trackName': 'Murray Bridge', 'State': 'SA'}, 
    {'trackCode': 511, 'trackName': 'Murray Bridge', 'State': 'SA'}, 
    {'trackCode': 600, 'trackName': 'Cannington', 'State': 'WA'}, 
    {'trackCode': 601, 'trackName': 'Mandurah', 'State': 'WA'}, 
    {'trackCode': 602, 'trackName': 'Northam', 'State': 'WA'}, 
    {'trackCode': 700, 'trackName': 'Hobart', 'State': 'TAS'}, 
    {'trackCode': 701, 'trackName': 'Launceston', 'State': 'TAS'}, 
    {'trackCode': 702, 'trackName': 'Devonport', 'State': 'TAS'}, 
    {'trackCode': 800, 'trackName': 'Darwin', 'State': 'NT'}, 
    {'trackCode': 900, 'trackName': 'Christchurch', 'State': 'NZ'}, 
    {'trackCode': 901, 'trackName': 'Wanganui', 'State': 'NZ'}, 
    {'trackCode': 902, 'trackName': 'Manawatu', 'State': 'NZ'}, 
    {'trackCode': 903, 'trackName': 'Auckland', 'State': 'NZ'}, 
    {'trackCode': 904, 'trackName': 'Waikato', 'State': 'NZ'}, 
    {'trackCode': 905, 'trackName': 'Otago', 'State': 'NZ'}, 
    {'trackCode': 906, 'trackName': 'Southland', 'State': 'NZ'}, 
    {'trackCode': 907, 'trackName': 'Wairarapa', 'State': 'NZ'}, 
    {'trackCode': 908, 'trackName': 'Wellington', 'State': 'NZ'}, 
    {'trackCode': 909, 'trackName': 'Tokoroa', 'State': 'NZ'}, 
    {'trackCode': 910, 'trackName': 'Taranaki', 'State': 'NZ'}, 
    {'trackCode': 911, 'trackName': 'Palmerston North', 'State': 'NZ'}, 
    {'trackCode': 912, 'trackName': 'Ashburton', 'State': 'NZ'},         
    ]


timeslot_mapping = {
    'Twilight': 't',
    'Morning': 'm',
    'Day': 'd',
    'Night': 'n'
    }


